### ISSUE TITLE
64-bit integers

### ISSUE THREAD

**Issue by l1a7t** [Fi1osof/modx-Dropbox#4]
В новой версии появилось, в старой не было.
Error while retrieving container list for the path "/" (The Dropbox SDK uses 64-bit integers, but it looks like we're running on a version of PHP that doesn't support 64-bit integers (PHP_INT_MAX=2147483647).  Library: "/core/components/dropbox/include/dropbox/lib/Dropbox/RequestUtil.php")

**Comment by Fi1osof** [comment]
Dropbox SDK работает только на 64-рехразрядных платформах. Обсуждалось в том числе и здесь: http://modxclub.ru/topics/dropbox-2.1.0-beta-1324.html#comment-4804

**Comment by Fi1osof** [comment]
P.S. на винде вообще php x64 отсутствует.

**Comment by l1a7t** [comment]
Спасибо. Система 64х битная, а PHP_INT_MAX как у 32бит, не понимаю почему, хоть с нуля систему ставь)

**Comment by Fi1osof** [comment]
@l1a7t у вас не винда?

**Comment by l1a7t** [comment]
Сервер на убунте, x86_64 GNU/Linux.

**Comment by Fi1osof** [comment]
Тогда совсем странно...

**Comment by l1a7t** [comment]
Буду разбираться, наверняка причина совсем банальная.
